/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 settings.gltf --transform 
Files: settings.gltf [103.43KB] > /Users/yunuskerestecioglu/Downloads/settings/settings-transformed.glb [105.22KB] (-2%)
Author: Center Additive Manufacturing (https://sketchfab.com/vitebsk3dprint)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gear-c2f82e5db44749149cd57dc65961a062
Title: Gear
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function SettingsModel(props) {
	const { nodes, materials } = useGLTF('/models/settings-transformed.glb')
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Object_2.geometry}
				material={materials['Scene_-_Root']}
				position={[10.703, 5.142, 6.337]}
				rotation={[-Math.PI, 0.222, -Math.PI]}
			/>
		</group>
	)
}

useGLTF.preload('/models/settings-transformed.glb')
