/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 stadium.gltf --transform 
Files: stadium.gltf [128.77KB] > /Users/yunuskerestecioglu/Downloads/stadium/stadium-transformed.glb [70.4KB] (45%)
Author: Awbmegames (https://sketchfab.com/Awbmegames)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-football-stadium-2ef76246010e435eafb316539cd9c260
Title: Low Poly Football Stadium
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function StadiumModel(props) {
	const { nodes, materials } = useGLTF('/stadium-transformed.glb')
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Football_Stadium_Color_0.geometry}
				material={materials.Color}
				position={[0.578, 18.586, 0.836]}
			/>
		</group>
	)
}

useGLTF.preload('/stadium-transformed.glb')
