/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 flags.gltf --transform 
Files: flags.gltf [25.5MB] > /Users/yunuskerestecioglu/Downloads/flags/flags-transformed.glb [2.24MB] (91%)
Author: George Jakeli (https://sketchfab.com/3djako)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flags-f2b7564377914552a6e080662795e6a0
Title: Flags
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function FlagsModel(props) {
	const { nodes, materials } = useGLTF('/models/flags-transformed.glb')
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.defaultMaterial.geometry}
				material={materials.Random_Mat6}
			/>
			<mesh
				geometry={nodes.defaultMaterial_1.geometry}
				material={materials.Random_Mat5}
			/>
			<mesh
				geometry={nodes.defaultMaterial_2.geometry}
				material={materials.Random_Mat4}
			/>
			<mesh
				geometry={nodes.defaultMaterial_3.geometry}
				material={materials.Random_Mat3}
			/>
			<mesh
				geometry={nodes.defaultMaterial_4.geometry}
				material={materials.Random_Mat2}
			/>
			<mesh
				geometry={nodes.defaultMaterial_5.geometry}
				material={materials.Random_Mat1}
			/>
			<mesh
				geometry={nodes.defaultMaterial_6.geometry}
				material={materials.Random_Mat}
			/>
		</group>
	)
}

useGLTF.preload('/models/flags-transformed.glb')
