/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 employee.gltf --transform 
Files: employee.gltf [114.3KB] > /Users/yunuskerestecioglu/Downloads/employee/employee-transformed.glb [8.64KB] (92%)
Author: zynxeror (https://sketchfab.com/zynxeror)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/psx-employees-only-metal-door-8bb63f0b0c454fe1b030ce6eb1031598
Title: psx "employees only" metal door
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function EmployeeModel(props) {
	const { nodes, materials } = useGLTF('/employee-transformed.glb')
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Object_7.geometry}
				material={materials.material_0}
			/>
		</group>
	)
}

useGLTF.preload('/employee-transformed.glb')
